repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, big2]
        files: ^big2/
      - id: ruff-format
        args: [big2]
        files: ^big2/
